# Upload ./src/emulator.bat to release

name: Release

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src/emulator.bat
            src/hello-world.asm
            LICENSE